### ISSUE TITLE
Fix typo from README file

### ISSUE THREAD

**Issue by horikandthepurpleshrooms** [aluxmanu/react-native-dialog-view#1]
There is a typo in the readme file under usage section
![image](https://github.com/aluxmanu/react-native-dialog-view/assets/37018766/e4c25f32-7b37-44b1-8ffc-50724bebf7cf)

**Comment by aluxmanu** [comment]
Fixed https://github.com/aluxmanu/react-native-dialog-view/commit/65b86c1a06579052bcf374f15f05aa44e541efe0
